#!/bin/bash

WORKDIR=/usr/local/go/src/github.com/groveriffic/go-prevalent-colors

docker run \
  --rm \
  -v "$PWD":"$WORKDIR" \
  -w "$WORKDIR" \
  --memory=512m \
  --cpus=1 \
  golang:1.11.4 \
  ./go-prevalent-colors \
    -n 5 \
    -cpu cpu.prof \
    -input fixtures/input.txt \
    -output out.csv \
    -log out.log
